### ISSUE TITLE
7segment

### ISSUE THREAD

**Issue by sewer159** [protaskin/AVRThermostat#1]
Hi.
Is it possible to easily change display with a common cathode on one with common anode?

**Comment by protaskin** [comment]
Hello!

Not without editing/rewriting the display "driver". And hardware-wise it would probably require using transistors to provide higher _output_ anode currents.

https://github.com/protaskin/AVRThermostat/blob/master/Thermostat/display.c
https://github.com/protaskin/AVRThermostat/blob/master/Thermostat/display.h
